[tool.poetry]
name = "ai-lab"
version = "0.1.0"
description = ""
authors = ["Szymon-SR <srszymonsr@gmail.com>"]
readme = "README.md"
packages = [{include = "ai_lab"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
